Merged PR 26142: Remove obsolete runtime source-build patch
This is causing the following build error

```
    /tarball/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/gen/EventSourceGenerator.Parser.cs(17,96): error CS0234: The type or namespace name 'DotnetRuntime' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?) [/tarball/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/gen/System.Private.CoreLib.Generators.csproj]

    /tarball/.dotnet/sdk/7.0.100-rc.1.22431.12/Microsoft.Common.CurrentVersion.targets(2071,5): error MSB4181: The "MSBuild" task returned false but did not log an error. [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]

        0 Warning(s)

        2 Error(s)
```